### ISSUE TITLE
[BUG]Steps available for donate but can't donate.

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#10]
**Describe the bug**
Steps available for donations but unable to donate and getting error.

**To Reproduce**
1. Home Page
2. Steps Donations
3. Donation Page

**Expected behavior**
It should be donate.

**Screenshots**

**Version Android 2.14.3:**

**Comment by parthanjaria** [comment]
@Pawanm1990 can you share screenshots of the flow or  a video.

**Comment by Pawanm1990** [comment]
pfa

Warm Regards,

Pawan Mishra
Company Secretary,
Impact - Your fitness + kindness app
www.impactapp.in
Phone: +91 9096090127

**Comment by AnujaPednekar** [comment]
@Pawanm1990 Can you please elaborate more on this issue?  
Like when u faced this issue whether u were part of JLL league or not?
What error did msg appear?

Please attach a screenshot of it, if you have taken it.

**Comment by AnujaPednekar** [comment]
![WhatsApp Image 2020-05-07 at 1 44 25 PM](https://user-images.githubusercontent.com/43374048/81537022-2d1f0900-938a-11ea-8913-a3e1e4eed60c.jpeg)

**Comment by AnujaPednekar** [comment]
![](https://files.slack.com/files-pri/T085NTUJK-F0136J77KUN/whatsapp_image_2020-05-07_at_1.44.25_pm__1_.jpeg)

**Comment by AnujaPednekar** [comment]
![WhatsApp Image 2020-05-07 at 1 44 25 PM (2)](https://user-images.githubusercontent.com/43374048/81537331-a74f8d80-938a-11ea-8fd6-cfd2bcd7a14e.jpeg)
![WhatsApp Image 2020-05-07 at 1 44 25 PM (1)](https://user-images.githubusercontent.com/43374048/81537338-a880ba80-938a-11ea-88ce-128b2c49e1c3.jpeg)

**Comment by AnujaPednekar** [comment]
Pawan: I'm on JLL league...went for donating steps but on donation page clicking on button but it's not working

**Comment by AnujaPednekar** [comment]
The bug occurred in previous versions where code to block passive donation was not added.
Working well current version.
