### ISSUE TITLE
streak break even after completing required distance

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#100]
Dear Team,
This is quite frustrating,
My streak broke again despite maintaining the run.
PFA the details.
I observed one instance when this happens
When I finish my active workout it counts the streak based on its KM.
Then I donate the steps as a passive workout, if the KM counted from the steps are less than the required KM to maintain the streak it resets the streak overwriting the results of earlier workout.
It does not add the KMs of current workout to the KMs of the earlier workouts of the same day.
Earlier it was doing so.
Kindly remove the bug permanently from the application.
Regards
Mahesh Baviskar

https://ced.impactrun.com/userdetail/198932
![202006 Streaks](https://user-images.githubusercontent.com/8169016/83843089-e8388900-a721-11ea-94c0-9ca12130f094.jpg)

**Comment by 24Kavisha** [comment]
179238
249577
@parthanjaria @sagrgpt pl check it on priority ( if possible)
Users reported this issue twice this week

**Comment by sagrgpt** [comment]
@24Kavisha This issue is set on high priority and set to be fixed and released with ver 2.16.7 expected date: 5/07/20

**Comment by parthanjaria** [comment]
Sent a new build 2.16.8.
The users with the similar issue if report streak break then please let us know. 
@24Kavisha @NishantKhandelwal1

**Comment by sagrgpt** [comment]
The changes made on the release 2.16.8 had an adverse effect on the app's functionality wrt to streak. We witnessed more users reporting irregular breaking of streak even though the km required were covered.

https://ced.impactrun.com/userdetail/577011
https://ced.impactrun.com/userdetail/298070
https://ced.impactrun.com/userdetail/151828
https://ced.impactrun.com/userdetail/278447

**Comment by parthanjaria** [comment]
Issue resolved in 2.16.17.1
