### ISSUE TITLE
[BUG] Can't donate passive steps

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#101]
**Describe the bug**
Unable to donate my steps. Check error toast in screenshot.

**To Reproduce**
1. Got the 9pm notification
2. Clicked on it and it took me to the screen to select a cause
3. Clicked on donate and it showed me the pop up (ss attached) (it did not go to the orange tick loading screen btw)
4. Closed the app, opened it again and clicked on the number of steps from the home screen
5. On the daily activity screen, clicked on the orange bottom bar.
6. Same things happened like step 3.

**Expected behavior**
I should be able to donate my steps, have the 'donating your steps' loading screen show up and the usual passive donation flow.

**Screenshots**
Ss- 
![Screenshot_20200607-230928](https://user-images.githubusercontent.com/64898571/83975992-af143a80-a914-11ea-9667-e6c2807091ef.jpg)

**Version [Check app's setting screen]:**
2.16.0.4

**Additional context**

**Comment by parthanjaria** [comment]
This happened beacuase the same day there was some issue at the backend related to donatioon API. If the issue reoccurs, feel free to reopen the issue.
