### ISSUE TITLE
[BUG] 'Calculating your steps' pop up not going away.

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#102]
**Describe the bug**
My friend got the 'calculating your steps' pop up and it wasnt going away from the notification drawer even after closing it, clicking it or opening the app.

**To Reproduce**
No steps as such, just got the pop up and didn't go away. Neither on clicking of it nor by dismissing it.

He opened the app too (didn't mention what actions he took) but didn't go either.

**Expected behavior**
Show either disappear if not available steps, or should follow the passive donation flow OR get dismissed if user dismisses it.

**Screenshots**
Adding 2 ss. One is the screenshot he sent. The other is the chat conversation.
![Screenshot_20200606-211138](https://user-images.githubusercontent.com/64898571/83976190-24ccd600-a916-11ea-9c52-8e0924e0259f.jpg)
![Screenshot_20200607-232527](https://user-images.githubusercontent.com/64898571/83976199-3910d300-a916-11ea-896b-bacb1e951b92.jpg)

**Version [Check app's setting screen]:**
2.15.3

**Additional context**
Name of friend -Nimish Mhatre

**Comment by sagrgpt** [comment]
Thanks for reporting this issue. We have picked it up at high priority. This will be solved in the next release.

**Comment by sagrgpt** [comment]
@kaziamina We have identified and fixed this issue for v2.16.7
Please reopen if you still face this issue in future versions.
