### ISSUE TITLE
While clicking on notification at notification center error message is coming

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#104]
**Describe the bug**
When I clicking on notification sometimes after clicking it shows unread and showing error message even if everything is working fine

**To Reproduce**
Click on the notification in notification center

**Expected behavior**
Error message should not come

**Screenshots**
Sent video to parth and Sagar

**Version [Check app's setting screen]:**
2.16.1

**Additional context**

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 We noticed that this issue has already been reported and fixed. Please search if an issue already exist before posting them. 
You can reopen the issue if it still exists in version prior to the one mentioned. 
Issue #97
