### ISSUE TITLE
[BUG] Leaderboard amount not increasing

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#108]
**Describe the bug**
I added 1000 steps with Step me App and donated 8Rs.
It reflected against my name on clicking the state name in league leaderboard but not total amount against the state name.
So, I repeated by adding 3000 steps again and the same thing happened.

Not adding steps to reproduce, the big description is clear...if any confusion, let me know.
Also, while we're at it, why am I still able to add steps from Step me?

**Screenshots**
![Screenshot_2020-06-16-19-49-18-233_com sharesmile share](https://user-images.githubusercontent.com/64792558/84787029-1ca62200-b00b-11ea-836f-881cc55730f1.jpg)
![Screenshot_2020-06-16-19-49-21-595_com sharesmile share](https://user-images.githubusercontent.com/64792558/84787041-1f087c00-b00b-11ea-86aa-2c72839ca78a.jpg)
![Screenshot_2020-06-16-19-49-43-960_com sharesmile share](https://user-images.githubusercontent.com/64792558/84787052-229c0300-b00b-11ea-9e5f-ddf1f06840f9.jpg)
![Screenshot_2020-06-16-19-49-47-349_com sharesmile share](https://user-images.githubusercontent.com/64792558/84787060-24fe5d00-b00b-11ea-8a24-7865696f7cac.jpg)

**Version [Check app's setting screen]:**2.16.4

**Additional context**

**Comment by sagrgpt** [comment]
@Share-Impact/backend-developers This is an expected behavior of cache? Please confirm.

**Comment by sagrgpt** [comment]
@Share-Impact/backend-developers Any comments?

**Comment by NishantKhandelwal1** [comment]
@sagrgpt this is expected behavior.
