### ISSUE TITLE
[BUG] Spacing on top of league banner

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#109]
**Describe the bug**
Before entering league, the banner has little space on top and on entering league it goes away.

Not adding steps, screenshots will clarify the issue.

**Screenshots**
![Screenshot_2020-06-16-19-55-50-501_com sharesmile share](https://user-images.githubusercontent.com/64792558/84787550-be2d7380-b00b-11ea-81a3-0f6009360691.jpg)
![Screenshot_2020-06-16-19-56-00-921_com sharesmile share](https://user-images.githubusercontent.com/64792558/84787562-c2f22780-b00b-11ea-8536-25fb262dd098.jpg)

**Version [Check app's setting screen]:** 2.16.4

**Additional context**

**Comment by sagrgpt** [comment]
@adrija25 Thanks for reporting this issue. Your issue has currently been shifted to low priority.

**Comment by parthanjaria** [comment]
issue resolved after 2.16.18
