### ISSUE TITLE
Multiple Step Donation - and Post in Team

### ISSUE THREAD

**Issue by ishannadkarni** [Share-Impact/Android-Impact-Issues#111]
**Describe the bug**
Tripti from GSK is a user for about 2 months now, and has created a team with her colleagues at work. They compete each day for daily distance and total distance.

I just got off a call with her, and she told me that after the update, multiple step donations are happening. A few of her colleagues have figured out that clicking on donate button multiple times very fast makes it count multiple times on the leaderboards. They call it in their group as a surprise bonus. Now while they take this as fun and joke about it, she said it breaks tracking trust in the app.

She says it’s back, after the update. She has noticed it in ios (her finance team colleagues, saw a 11x on 11 clicks in one of the instances) and Samsung phone (her phone, happened twice).

To Reproduce
1. Open app
2. Quick click on Donate Steps
3. See the Post on Team

Expected behavior
Only single step donation needs to happen

**Screenshots**
![image](https://user-images.githubusercontent.com/64792502/85002815-02875380-b173-11ea-8248-59b74d8411ce.jpeg)

**Version [Check app's setting screen]:**
Samsung phone - User -Tripti from the above team (screenshot)

**Additional context**
Happens in iOS too. Max occurance- 11 multiple donations counted.

**Comment by sagrgpt** [comment]
Multiple passive workouts are present in production for versions >= 2.16.*

**Comment by sagrgpt** [comment]
This issue has been resolved. However, another issue related to multiple passive donation was recognized during the resolution. I have created a sister issue #147 for the same and posted it on the backend board. 
Any update will be further carried forward in the above mentioned issue.
