### ISSUE TITLE
[BUG] Not able to login

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#115]
**Describe the bug**
Installed the app today and tried to log in with one of my other previously registered unused Gmail id- adrija250195@gmail.com.
It didn't allow me to log in.
I am not logged in any other device

Check the video in-app testing channel.

**Version [Check app's setting screen]:** 2.16.6

**Additional context**

**Comment by adrija25** [comment]
Still facing the same issue @sagrgpt @parthanjaria @AnujaPednekar 
![Screenshot_2020-07-03-21-10-53-137_com sharesmile share](https://user-images.githubusercontent.com/64792558/86483606-066dc500-bd72-11ea-90d8-3e2a3c9d0b60.jpg)

**Comment by sagrgpt** [comment]
https://sharesmile.slack.com/files/UBNK3BHT7/F015HUAMH39/screenrecorder-2020-06-24-15-25-37-612.mp4

**Comment by adrija25** [comment]
My slack is deactivated.

**Comment by adrija25** [comment]
My slack is deactivated but I am still facing the issue.
So if you need any other recording let me know via WhatsApp.

**Comment by parthanjaria** [comment]
Issue has been resolved from backend.
