### ISSUE TITLE
[BUG] Can't see team list or refresh team

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#117]
**Describe the bug**
I'm a captain of a team but manage team page is not opening, the team page is not refreshing and I'm not getting any notification of join request

**To Reproduce**
1. Go to Teams
2. Open a team you're a captain of
3. Click on manage team
4. Try to refresh the team main page

**Expected behavior**

**Screenshots**
Video shared on slack

**Version [Check app's setting screen]:**
2.16.6.1

**Additional context**

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 I hope you are already looking into this. Please let us know the update.

**Comment by NishantKhandelwal1** [comment]
It doesn't look like a team related bug. Server was high that time(10:30-11:10) and due to this request was failing.

![impact_no…_env_production_Datadog](https://user-images.githubusercontent.com/19950800/85824001-5eb62d00-b79c-11ea-9a34-3074eef8a23e.png)

**Comment by NishantKhandelwal1** [comment]
Closing this issue.. Feel free to open if you face again
