### ISSUE TITLE
[BUG] Unable to start Active Workout if device has no internet connectivity

### ISSUE THREAD

**Issue by nik6018** [Share-Impact/Android-Impact-Issues#118]
**Describe the bug**
If the device has no internet connectivity, pressing the **Indoor Workout** CTA on the cause card show's me G-Fit permission screen to allow step tracking, if I click on allow it gives me a toast with **Permission Denied** this error msg.

Killing & restarting the app has the same behaviour.

If I turn on internet connectivity, I am able to start the workout without any issues.

**To Reproduce**
1. Turn off internet connectivity 
2. Start Active Workout
3. Instead of the countdown screen you'll see G-Fit permission screen
4. Clicking allow shows me the **Permission Denied** err msg 

**Expected behavior**
User should be able to start Active Workout even without internet connectivity

**Version [Check app's setting screen]:**
_2.16.4_

**Additional context**
Not able to reproduce this issue again with the same steps

**Comment by parthanjaria** [comment]
@nik6018 Please update the app to 2.16.15 version and let us know if the issue still persists.
