### ISSUE TITLE
UI is not correct in small size mobile

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#119]
**Describe the bug**
Ui was not correct 

**To Reproduce**
sharing screenshots

**Expected behavior**

**Screenshots**
![WhatsApp Image 2020-06-26 at 5 57 37 PM](https://user-images.githubusercontent.com/19950800/85857521-aa39fc80-b7d7-11ea-85e1-9c0c06028c38.jpeg)
![WhatsApp Image 2020-06-26 at 5 51 01 PM (1)](https://user-images.githubusercontent.com/19950800/85857523-ab6b2980-b7d7-11ea-9b1c-395653eff148.jpeg)
![WhatsApp Image 2020-06-26 at 5 51 01 PM](https://user-images.githubusercontent.com/19950800/85857525-ad34ed00-b7d7-11ea-912d-ed018178bc5d.jpeg)
![WhatsApp Image 2020-06-26 at 5 51 00 PM](https://user-images.githubusercontent.com/19950800/85857530-aefeb080-b7d7-11ea-8ff3-073e0c13e766.jpeg)

**Version [Check app's setting screen]:**
2.16.7
iTel A41
**Additional context**

**Comment by sagrgpt** [comment]
This issue is either due to support of low end api levels which are in discussion for removal or else, this is due to incorrect handling of text scaling (dp/px) during UI implementation on the platform. 
Setting priority level to low and adding it to the product backlog for future project reference.

**Comment by sagrgpt** [comment]
UI issues such as these will be taken care of while the UI upgrade project. Closing the issue. Please keep adding UI mishaps for future reference.

**Comment by sagrgpt** [comment]
Screenshot_20200730-004131](https://user-images.githubusercontent.com/11998999/91536091-d259ef00-e931-11ea-87bc-52b5c2855393.jpg)
![Screenshot_20200715-003343](https://user-images.githubusercontent.com/11998999/91536098-d4bc4900-e931-11ea-88c0-fcd2db6a2a78.jpg)
