### ISSUE TITLE
[BUG] App opens at random old screens that I visited

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#122]
**Describe the bug**
Whenever I open the app, it sometimes opens at screens that I had visited few hours ago. Like the passive donation screen, Manage teams screen, and sometimes a team's post. This happens even when I don't leave the app at that screen.

**To Reproduce**
1. Open the App
2. Check whether it opened or homepage or not!

**Expected behavior**
The app should open on screen where I left it or on the homepage

**Screenshots**
![Screenshot_20200626-215207](https://user-images.githubusercontent.com/64794993/86346658-e14a5b00-bc7a-11ea-90ff-ecbea4231092.jpg)

**Version [Check app's setting screen]:**
2.16.6.1

**Additional context**
NA

**Comment by sagrgpt** [comment]
The app's back stack is correctly implemented and have no reason for this behavior. Neither is this reproduceable. 
Please open this issue if you face it again.
