### ISSUE TITLE
active not recording, steps done during active goes into passive[BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#126]
When i am starting workout after starting it is not capturing the steps and when i am checking the same after ending workout it is showing in passive steps.
Please check

https://impactapp.freshchat.com/a/154002725929316/inbox/3/0/conversation/305287835594601

https://ced.impactrun.com/userdetail/300921

**Comment by AnujaPednekar** [comment]
Is he ending the workout after 12 am?

**Comment by sagrgpt** [comment]
This issue is resolved on version post 2.16.3. I have checked with the user as well. He is not facing this issue anymore.
