### ISSUE TITLE
User Id - 125197 Multiple Workouts not added

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#127]
User Id : 125197 
Moti Singh one of our user facing issue in global ranking and multiple workouts of 28th and 30th June not added in Workouts history, chart. Even this amount not added on total. 
Version 2.19.9.1
Motorola x4
As discussed with Anuja, she said it will be resolved in next build.
Please find the user feedback......
Ver-2.19.9 Update par            pahel *97578* tha
Update ke baad ver-2.19.9.1itna show huwa  *97708*
Means *97708-97578*= *130*
 
Sirf 30th June ka add huwa 13km130

28th ka huwa hi nahi 
10.2km 102 ?
 
Please find the attached
![IMG-20200710-WA0001](https://user-images.githubusercontent.com/64827333/87127166-1a05b800-c2ab-11ea-91fa-55441caea3d0.jpg)
![IMG-20200710-WA0000](https://user-images.githubusercontent.com/64827333/87127201-30137880-c2ab-11ea-90ee-51502dfc9eb9.jpg)
![IMG-20200710-WA0001](https://user-images.githubusercontent.com/64827333/87127223-3ace0d80-c2ab-11ea-9e83-e21120d3b438.jpg)
![IMG-20200710-WA0002](https://user-images.githubusercontent.com/64827333/87127239-43264880-c2ab-11ea-9b7e-0bfc2b69f244.jpg)

**Comment by AnujaPednekar** [comment]
This user issue is resolved from backend but the underlying reason is multiple active workouts are created with same client run id

**Comment by parthanjaria** [comment]
The multiple workout issue is resolved in 2.16.4. If the issue still persists then please feel free to reopen the issue.

**Comment by sagrgpt** [comment]
The multiple workout issue is resolved in **2.16.14**
