### ISSUE TITLE
profile stat league mismatch [BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#131]
in my profile the total amount shown is Rs.2623 but in league (my group ) the amount shown is 2423. So kindly look into the matter and add Rs.200 to my league amount.

https://impactapp.freshchat.com/a/154002725929316/inbox/0/0/conversation/377673528316436
https://ced.impactrun.com/userdetail/718975/

**Comment by parthanjaria** [comment]
The issue has been resolved from backed. @nikhilk90 let us know if the issue still perists.
