### ISSUE TITLE
[BUG] Project link in feed not working

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#132]
**Describe the bug**
The project link for Vesta in feed is not working.
On multiple click feed shows network error.
My network is fine.
Tried both wifi and mobile data.

**Screenshots**
![Screenshot_2020-07-17-14-16-57-387_com sharesmile share](https://user-images.githubusercontent.com/64792558/87768064-3b315000-c839-11ea-8922-eb7d4dba9ff9.jpg)
![Screenshot_2020-07-17-14-17-00-268_com sharesmile share](https://user-images.githubusercontent.com/64792558/87768078-3ec4d700-c839-11ea-926c-6c8ef9cc9d38.jpg)
![Screenshot_2020-07-17-14-18-20-633_com sharesmile share](https://user-images.githubusercontent.com/64792558/87768086-41273100-c839-11ea-9b08-8f464944ff30.jpg)

**Version [Check app's setting screen]:** 2.16.9

**Additional context**

**Comment by AnujaPednekar** [comment]
Can you please retry, working for me

**Comment by adrija25** [comment]
![Screenshot_2020-07-29-19-31-16-499_com.sharesmile.share.jpg](https://user-images.githubusercontent.com/64792558/88809838-30c86c00-d1d2-11ea-863f-a8689c962cdd.jpg)

Not working
Everything else working fine.

**Comment by sagrgpt** [comment]
@AnujaPednekar It's not working in my device as well. Please check,

**Comment by parthanjaria** [comment]
This is working fine in multiple devices. Must be some network issue. If issue still persists then feel free to reopen the issue.

**Comment by sagrgpt** [comment]
This issue still exists. As discussed with @AnujaPednekar , there is a specific use case to replicate this issue.

**Comment by NishantKhandelwal1** [comment]
Project link is working. We have to wait a few moments then it will open

**Comment by sagrgpt** [comment]
**Steps to reproduce the issue**: 
1. Open "Building Green Sand Beach to fight off the climate Crisis" blog in the feed
2. Scroll down to the hyperlink in the blog. 
3. Click on the link twice with a gab of 1-2 sec between the clicks. 
4. Poor Connection screen is now visible. **[ERROR]**
5. If the does not appear then press back and try step 3 again.

**Comment by AnujaPednekar** [comment]
After clicking the link twice all the resources are getting loaded double times hence page loading taking more and we stop loading that page. 
Solution: I have increased the time limit.
