### ISSUE TITLE
donation is coming 0 but money is showing more[BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#134]
"Sir my workout is starting from
Huge amount
Please look into it and solve my problem
Because of that problem I am not doing impact
But donation is coming 0 but money is showing more"

https://impactapp.freshchat.com/a/154002725929316/inbox/0/0/conversation/376669895280637

**Comment by sagrgpt** [comment]
Similar issue is being faced with user https://ced.impactrun.com/userdetail/80695
[Click here for images related to this issue](https://github.com/Share-Impact/Android-Impact-Issues/files/4999810/WhatsApp.Unknown.2020-07-30.at.1.29.12.PM.zip)

**Comment by sagrgpt** [comment]
We are resolving this issue with the release of **v2.16.13**. If you still face the problem in or above the mentioned version feel free to reopen this issue.
