### ISSUE TITLE
[BUG] Playstore shows app update option even after I updated the app

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#142]
I have updated the app, reinstalled the app.
Yet the option to update it doesn't go away.
On click it shows Open and uninstall options.
I am not sure if it's play store issue or Impact's.
Haven't faced with any other app.
Been happening for a month now.

![Screenshot_2020-07-30-16-16-49-028_com android vending](https://user-images.githubusercontent.com/64792558/88914588-7b082680-d280-11ea-876d-5ed93b614748.jpg)
![Screenshot_2020-07-30-16-16-57-295_com android vending](https://user-images.githubusercontent.com/64792558/88914965-14373d00-d281-11ea-90f9-f686c394fb2a.jpg)
![Screenshot_2020-07-30-16-17-13-148_com sharesmile share](https://user-images.githubusercontent.com/64792558/88914983-1ac5b480-d281-11ea-8faf-ec0166e3926c.jpg)

**Comment by sagrgpt** [comment]
This is an issue from the play store side. This is possible as you are an internal user of the application and have versions not in the correct order which is not the issue for our production users.
