### ISSUE TITLE
Photo not coming up in leaderboard[BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#144]
https://impactapp.freshchat.com/a/154002725929316/inbox/0/0/conversation/378069198648527

![img_1595057348299](https://user-images.githubusercontent.com/8169016/89024237-6ab88000-d342-11ea-8f92-7c0dc40f333a.jpeg)
![img_1595057294037](https://user-images.githubusercontent.com/8169016/89024257-6e4c0700-d342-11ea-8202-f8823e9e8d4d.jpeg)

**Comment by parthanjaria** [comment]
can you share which team this user is in? @nikhilk90

**Comment by parthanjaria** [comment]
@nikhilk90 unable to contact the user. I have messaged him from whatsapp, but no reply. I saw from postman, there seems to be no issue there.

**Comment by parthanjaria** [comment]
The issue is resolved, as talked with the user. Please feel free to reopen the issue if still persists.
