### ISSUE TITLE
[BUG] Completed Cause button showing Start Workout

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#15]
**Describe the bug**
On home page completed cause button showing start workout. On click on that tell your friends share option coming.

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'Completed Cause button'
3. Scroll down to 'Cause Home Page'

**Expected behavior**
"Tell Your Friends" option should come.

**Screenshots**
![Screenshot_20200506-172807](https://user-images.githubusercontent.com/64827333/81183170-72c78480-8fcc-11ea-9bca-bd7678fbe5ad.png)

**Version [Check app's setting screen]:**
Android 2.14.3

**Additional context**
NA

**Comment by parthanjaria** [comment]
@Pawanm1990 can you share the screen recording of this.

**Comment by Pawanm1990** [comment]
pfa

Warm Regards,

Pawan Mishra
Company Secretary,
Impact - Your fitness + kindness app
www.impactapp.in
Phone: +91 9096090127

**Comment by AnujaPednekar** [comment]
Solution: Checking user is not of the non-impact league by using shared preference value.
