### ISSUE TITLE
User Id - 44017 streak not maintained but showing streak is maintained

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#150]
**Describe the bug**
User Id - 44017 
Username - Adrija Chowdhury
streak not maintained but showing streak is maintained

**To Reproduce**

**Expected behavior**
It should be streak not maintained

**Screenshots**
![IMG-20200821-WA0000](https://user-images.githubusercontent.com/64827333/90859783-77128480-e3a6-11ea-993e-7e33d74fac84.jpg)
![IMG-20200821-WA0001](https://user-images.githubusercontent.com/64827333/90859818-898cbe00-e3a6-11ea-83f3-cf106240a2e9.jpg)

**Version [Check app's setting screen]:**
2.16.11 (Redmi note 7pro)

**Additional context**

**Comment by parthanjaria** [comment]
App issue resolved in 2.16.17.1. Please reopen the issue if still persists?
