### ISSUE TITLE
[BUG] App crashing on clicking global leaderboard

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#153]
**Describe the bug**
App crashing on clicking global leaderboard and more option
Screen recording shared in app testing channel.
Posting screenshot below
.

**Screenshots**
![Screenshot_2020-08-30-00-35-55-031_com miui home](https://user-images.githubusercontent.com/64792558/91644423-6b375a00-ea59-11ea-8205-42cd54f9af30.jpg)

**Version [Check app's setting screen]:** 2.16.17.2

**Additional context**

**Comment by sagrgpt** [comment]
Crashes are automatically reported to us. Hence, You need not report them separately. 
We're working on this crash and will be fixed in the upcoming version

**Comment by adrija25** [comment]
@sagrgpt okay but still facing it. Fyi
