### ISSUE TITLE
[BUG] Duplicate passive workout

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#155]
**Describe the bug**
Received goal completion notification so I opened to check my today's steps. I was sure I've not done 1250 steps but it showed 1246 and 1 km complete. Checked workout history and passive donation of 623 steps is counted twice.

**To Reproduce**
1. No idea how to reproduce

**Expected behavior**

**Screenshots**

**Version [Check app's setting screen]:**
2.16.17.4
![Screenshot_20200904-213146](https://user-images.githubusercontent.com/64794999/92261209-affa3f80-eef6-11ea-99b0-09bfe2de11fe.png)

**Additional context**

**Comment by kanakagr** [comment]
![Screenshot_20200904-213112](https://user-images.githubusercontent.com/64794999/92261352-ea63dc80-eef6-11ea-856c-ac987db0eb6b.png)

**Comment by sagrgpt** [comment]
This issue is related to two different issue: 
- Issue #145 
- Issue #147
