### ISSUE TITLE
[BUG] Teams comment time showing incorrect

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#17]
**Describe the bug**
I did comment at 7.27 pm but it showing 7.09 pm.

**To Reproduce**
1. Go to 'Teams Page.'
2. Click on 'Best Friend Teams'
3. Scroll down to 'Teams

**Expected behavior**
It should be on actual time.

**Screenshots**
![Screenshot_20200506-192725](https://user-images.githubusercontent.com/64827333/81186763-d489ed80-8fd0-11ea-8283-f4daca4e322d.png)

**Version [Check app's setting screen]:**
2.14.3

**Additional context**
NA

**Comment by parthanjaria** [comment]
Not an issue.

**Comment by sagrgpt** [comment]
@parthanjaria If an issue is incorrect or invalid, please change it's label to same so that this is not counted in our defect metric calculation.
