### ISSUE TITLE
[BUG]Daily Stats and Global leaderboard Last 7 days data does not match

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#19]
**Describe the bug**
I might be wrong but I noticed that the data visible in my stats -weekly and the global leaderboard for the last 7 days..don't match.
My stats shows Rs10 (weekly) and Global leaderboard shows Rs17..My total in the month of May is Rs16.
I am not sure if it's a bug or not.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen

**Screenshots**
![Screenshot_2020-05-08-12-47-08-932_com sharesmile share](https://user-images.githubusercontent.com/64792558/81381522-7ec95880-912a-11ea-9ba1-51e1deef77c7.jpg)
![Screenshot_2020-05-08-12-47-14-605_com sharesmile share](https://user-images.githubusercontent.com/64792558/81381631-a3bdcb80-912a-11ea-9265-cc7679f41323.jpg)

**Version [Check app's setting screen]:**2.14.0

**Additional context**

**Comment by parthanjaria** [comment]
This is a duplicate issue as of #116
