### ISSUE TITLE
[BUG] Streak ring showing complete status even when goal not achieved

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#20]
**Describe the bug**
Streak ring showing complete progress on the activity page in post workout flow even when the goal is not completed.

**To Reproduce**
1. Start workout
2. Click on Stop workout
3. Check ring progress on streak page

**Expected behavior**
It should show the actual progress

**Screenshots**
![Screenshot_20200508-140640](https://user-images.githubusercontent.com/64794993/81388558-13858380-9136-11ea-80be-1fcffb8afb3c.jpg)

**Version : 2.14.4.0
**

**Additional context**

**Comment by sagrgpt** [comment]
Unable to reproduce. 
@parthanjaria Can you give a look?

**Comment by parthanjaria** [comment]
Solution : 
After the workout is completed there was a calculation mistake of km and m. 

val activeDistance = (cachedData.activeDistance*1000) + recentActiveWorkout.distance made this change.
