### ISSUE TITLE
[BUG] Network error and technical difficulty toast while entering and exiting league

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#23]
**Describe the bug**
Getting network error when trying to enter JLL league and technical difficulty error when trying to exit. It works after trying multiple times but got the error quite frequently.

**To Reproduce**
1. Go to 'League'
2. Enter code 'jlla3'
3. Try exiting

**Expected behavior**
A smooth enter and exit experience.

**Screenshots**

**Version [Check app's setting screen]:**
2.14.4

**Additional context**

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 Check if this is not the same issue that we resolved that day.

**Comment by sagrgpt** [comment]
@kanakagr Are you still facing this issue?

**Comment by kanakagr** [comment]
No. Not facing now

**Comment by sagrgpt** [comment]
This might either be a genuine network error or was fixed due to the recent hotfix changes. 
Closing this issue. Feel free to reopen if you face the issue again.
