### ISSUE TITLE
Duplicate Workouts

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#24]
CED Link : https://ced.impactrun.com/userdetail/518106

**Comment by sagrgpt** [comment]
@AnujaPednekar Please check if this is on a version before or after your new passive donation implementation that attempted to fix this issue.

**Comment by nikhilk90** [comment]
Actually please check whether this is duplicate workout issue or different one... By looking at other cases it seems some guys are adding exact same  steps in few seconds interval.

**Comment by nikhilk90** [comment]
this one should be higher priority issue 
more than 500 duplicates workouts in a day.

**Comment by parthanjaria** [comment]
The issue is solved in v2.15.2
Please feel free to report if the issue still persists
