### ISSUE TITLE
[BUG] I entered into JLL league but Vedanta cause was visible.

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#27]
**Describe the bug**
I entered into JLL league but Vedanta cause was still visible and I could start a workout. After I ended the workout, I was automatically logged out from the league. Entered again and vedanta's cause was still visible. 

**To Reproduce**
1. Go to 'League and enter code jlla1

**Expected behavior**
No cause should be visible

**Screenshots**

**Version [Check app's setting screen]:**
2.14.4

**Additional context**

**Comment by sagrgpt** [comment]
**Steps to reproduce:**
1. Open the app.
2. Non jll cards are visible even though I'm part of the league. 
3. Click on league tab. 
4. Jll league team leader board is visible. 
5. Refresh the leaderboard. 
6. JLL league leaderboard is refreshed. 
7. Click on home screen and start indoor workout (select indoor option from dialog). 
8. Grant gfit permission if asked for. 
9. Start indoor workout. 
10. End indoor workout..
11. Click ok if popup appears. 
12. Click on league tab
13. No more part of the JLL league. Automatically exited! League selection page is now visible. 
14. Enter league code and click submit. 
15. JLL league joined.
16. Refresh league. Leaderboard refreshed. 
17. Click on profile tab
18. Amount still viaible as main matric. 
19. Click on homescreen tab
20. All non jll causes are still visible with option to choose between indoor and outdoor workout.

**Comment by sagrgpt** [comment]
[](https://files.slack.com/files-pri/T085NTUJK-F0141KZLLTS/download/67614b60-0b8e-4b4e-8c12-1f340ecb0fba.mp4)

**Comment by parthanjaria** [comment]
Solution : Delete the causes when the user enters a non-impact league.
