### ISSUE TITLE
[BUG] App crashes on passive donation screen

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#29]
**Describe the bug**
App crashes on passive donation screen

**To Reproduce**
1. Go to streak page
2. Click on donation button at bottom
3. UI shows without any cause and crashes instantly

**Expected behavior**
Passive donation page should show causes to donate steps

**Screenshots**
Couldn't take screenshot because app crashes instantly

**Version [Check app's setting screen]:**
2.14.5

**Additional context**
NA

**Comment by sagrgpt** [comment]
@aayush-khandelwal Were you a part of JLL league when this happened?

**Comment by aayush-khandelwal** [comment]
No

**Comment by sagrgpt** [comment]
For more details on the crash [click here](https://console.firebase.google.com/project/run-for-a-cause/crashlytics/app/android:com.sharesmile.share/issues/88e73aca0ada91c7a3d436106ba1cebc?time=last-seven-days&sessionId=5EB8115901750001157829D44059ABB4_DNE_0_v2&sessionTab=data&userInfoQuery=3124).

**Comment by sagrgpt** [comment]
@parthanjaria This is mostly because of the recent changes done by you in the causeAdapter

**Comment by sagrgpt** [comment]
@parthanjaria We might have to push a hotfix if this is an existing and recurring issue on the live build.

**Comment by parthanjaria** [comment]
The issue is already solved and a build is pushed. 2.14.6.

@aayush-khandelwal please update and check the issue.

**Comment by aayush-khandelwal** [comment]
Yes. Not reproducing in current build
