### ISSUE TITLE
Google Fit step addition not working

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#30]
**Describe the bug**
In the testing session, my passive steps showed a different number before the workout, after the workout and even after the second workout I did. 

**To Reproduce**
1. Click on number of steps on the home page
2. View the number of active and passive steps
3. Start indoor workout (by making it default mode)
4. Workout and finish the workout
5. The numbers in the post workout DAS should reflect the new active and passive steps (but they don't)
6. Click on continue and it took me directly to the homepage
7. Click on the number of steps again from the homepage and check the number of steps again
8. The number of 'todays' donatable steps also goes down to zero after the workout.

![Screenshot_20200511-121019](https://user-images.githubusercontent.com/64898571/81532071-728b0880-9381-11ea-8003-12e9209e9e45.jpg)
![Screenshot_20200511-121205](https://user-images.githubusercontent.com/64898571/81532072-73239f00-9381-11ea-95b3-82a0c23019c8.jpg)

**Expected behavior**
The passive distance should have remained or increased but not decreased throughout the sessions

**Screenshots**
Attaching screenshots.

**Version [Check app's setting screen]:**

**Additional context**
This was in the build that's Sagar had a quick testing session around.

![Screenshot_20200511-121232](https://user-images.githubusercontent.com/64898571/81532063-7028ae80-9381-11ea-9a1b-d63e2f29db31.jpg)
![Screenshot_20200511-121246](https://user-images.githubusercontent.com/64898571/81532070-71f27200-9381-11ea-8e09-bf08f98cadd7.jpg)

**Comment by sagrgpt** [comment]
@kaziamina We have identified and fixed this issue. Please test v2.15.0.0 to ensure the same.
Closing this issue now. You are welcome to re-open the issue if the above-mentioned version fails your test.

Here's a quick suggested test: 

1. Take a screenshot(ss) of DSA 
2. Start workout 
3. Complete at least a min workout and end the workout 
4. Take a ss of the DSA during end workout flow 
5. Open DSA and take a ss. 
6. Comparing the 3 DSA should be incremental and the math should add up.
