### ISSUE TITLE
[BUG] Too short popup issue

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#32]
**Describe the bug**
Too short pop-up came even after completing 134 steps and 1rs raised.

**To Reproduce**
1.
Start indoor workout by making it the default mode.
2. Stop the workout at 128 steps and got the 'too short' popup
3. Clicked no and continued workout and repeat step 2 till 134 steps.
4. At 136 steps it showed me the 'end workout' popup

**Expected behavior**
Workout should end successfully without the too short pop-up when I've completed the minimum number of steps and amount raised.

**Screenshots**
![Screenshot_20200511-121055](https://user-images.githubusercontent.com/64898571/81532630-5176e780-9382-11ea-87de-7c04e57bb953.jpg)
.

**Version [Check app's setting screen]:**
Sagar's testing session

**Additional context**

**Comment by sagrgpt** [comment]
Hi @kaziamina,
It seems you have created a duplicate issue. Closing this issue. Future updates will be posted to issue #31
