### ISSUE TITLE
[BUG] glitch on runscreen

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#33]
**Describe the bug**
There is a glitch when we turn on the workout and land on the run screen after the countdown.

**To Reproduce**
1. Start workout
2. Allow the countdown to start
3. See the glitch (pay attention to the distance text)

**Expected behavior**
No visual glitch in the ui

**Screenshots**
![Screenshot_20200511-122530](https://user-images.githubusercontent.com/64898571/81533915-ad427000-9384-11ea-881e-e65f873a39e4.jpg)
![Screenshot_20200511-122540](https://user-images.githubusercontent.com/64898571/81533917-af0c3380-9384-11ea-8c5c-2ee4faefce8b.jpg)

**Version [Check app's setting screen]:**
Sagar's testing session

**Additional context**

**Comment by sagrgpt** [comment]
@kaziamina We have identified and fixed this issue. Please test v2.15.0.0 to ensure the same.
Closing this issue now. You are welcome to re-open the issue if the above-mentioned version fails your test.
