### ISSUE TITLE
[BUG] Random characters displayed in daily activity screen

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#35]
**Describe the bug**
On clicking on 'number of steps' after doing a workout, the DAS screen showed random characters in place of distance for a couple of milliseconds.

**To Reproduce**
1. Finish workout
2. From the homepage go to today's steps
3. The random characters appeared here before the actual numbers showed

**Expected behavior**
No glitch in the display of numbers

**Screenshots**
![Screenshot_20200511-124716](https://user-images.githubusercontent.com/64898571/81534745-2bebdd00-9386-11ea-8b14-0155bb839810.jpg)
![Screenshot_20200511-124842](https://user-images.githubusercontent.com/64898571/81534751-2db5a080-9386-11ea-8ce4-aac6ea341869.jpg)

**Version [Check app's setting screen]:**

**Additional context**

**Comment by parthanjaria** [comment]
@kaziamina can you mention the version of the app?

**Comment by sagrgpt** [comment]
@parthanjaria I'm working on this issue. I have the version number with me. Will be updating them soon.

**Comment by sagrgpt** [comment]
@kaziamina We have identified and fixed this issue. Please test **v2.15.0.0** to assure that this issue is resolved. Closing this issue now. You are welcome to re-open the issue if the above-mentioned version fails your test.
