### ISSUE TITLE
[BUG] Random numbers in the passive steps and total donatable steps

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#36]
**Describe the bug**
Various combinations of number of steps in passive and donatable steps.

**To Reproduce**
It's a lottttt of steps, please refer to the video shared to Sagar. 

**Expected behavior**
The number of steps should remain constant if I'm not doing any workout.

**Screenshots**
I am attaching the screenshots but please check the video to understand the steps.
![Screenshot_20200511-124716](https://user-images.githubusercontent.com/64898571/81534967-9270fb00-9386-11ea-8c26-1742326825cb.jpg)
![Screenshot_20200511-124703](https://user-images.githubusercontent.com/64898571/81534974-943abe80-9386-11ea-9dee-37014a13ef43.jpg)
![Screenshot_20200511-124630](https://user-images.githubusercontent.com/64898571/81534975-94d35500-9386-11ea-877d-ee7b2159ae46.jpg)

**Version [Check app's setting screen]:**
Sagar's testing session

**Additional context**

**Comment by kaziamina** [comment]
Please look at Issue number 30 to have a better understanding of how the stats looked before I did the outdoor workout

**Comment by sagrgpt** [comment]
@kaziamina The issue mentioned here is a known limitation of the system in place. The fixes done recently for v2.15.0.0 attempts at making this a less frequent occurrence.
Closing the issue for now. Please re-open if this is still happening frequently for v2.15.0.0 or above.
