### ISSUE TITLE
[BUG] Unable to track passive steps

### ISSUE THREAD

**Issue by 24Kavisha** [Share-Impact/Android-Impact-Issues#37]
**Describe the bug**

457890 - User is not receiving passive steps. Android

**To Reproduce**
Unknown

**Expected behavior**
Every step that a user takes without turning on an active workout, should be counted as passive steps.

**Screenshots**
NA

**Version [Check app's setting screen]:** Ver- 2.14.6

**Additional context**
NA

**Comment by sagrgpt** [comment]
@24Kavisha please follow the template while reporting a bug.

**Comment by sagrgpt** [comment]
@24Kavisha please get the following screenshot from the user:
1. Screen shot of the homescreen
2. Screenshot of the daily activity screen. 
3. Check if user is using any other app(preferencially GFit) for tracking his/her workout. If yes, please get the screenshot of the app screen that displays users steps & distance for the day.

**Comment by AnujaPednekar** [comment]
Checked her record on CED today. Passive is working for her now.

**Comment by AnujaPednekar** [comment]
Please reopen this issue if faced again
