### ISSUE TITLE
Achievements in profile infinite loading[BUG]

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#4]
**Describe the bug**
Achievement section is only loading infinitely and not showing any badges

**To Reproduce**
1. Go to profile
2. See loading

**Expected behavior**
few seconds of loading then badges should appear

**Screenshots**
screenshots attached 

**Smartphone (please complete the following information):**
 - OS: -
- Device RMX1901
 - 
<img width="963" alt="Screenshot 2020-05-05 at 9 35 15 AM" src="https://user-images.githubusercontent.com/8169016/81034566-33f2db00-8eb5-11ea-9943-ceb652c30696.png">
App version 518 (2.13.6)

CED : https://ced.impactrun.com/userdetail/521254

**Comment by parthanjaria** [comment]
@nikhilk90 if we have the contact of the user, can we ask him to logout and then login. The achievements are not loading because the badge data is not loaded. Once that data is loaded, it will load the achievements.

**Comment by sagrgpt** [comment]
Since more information is required on this issue. This issue has been shifted to low priority. 
@nikhilk90 Let us know if you want to shift it to a higher priority.

**Comment by adrija25** [comment]
@nikhilk90 if it's samsung, clearing cache and data resolves it...every single time.
It has been reported 5 times (Samsung device) and this solution has worked every single time.

**Comment by sagrgpt** [comment]
@parthanjaria Where are we on the badge issues?

**Comment by sagrgpt** [comment]
Hi, let's stick to having this issue for **achievement not loading in profile**
I have created a separate issue on [achievement badges](https://github.com/Share-Impact/Android-Impact-Issues/issues/26) and added @nikhilk90 and @adrija25 Let's continue the conversation there.

**Comment by nikhilk90** [comment]
Wahi toh tha starting se 🧐

**Comment by sagrgpt** [comment]
This issue is resolved on version 2.16.*
