### ISSUE TITLE
[BUG] Teams page visible from Deeplink even after being part of JLL

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#40]
**Describe the bug**
Was able to see teams listing page through a deeplink created by Parth for testing even when I was part of JLL League
https://impactapp.page.link/createTeam

**To Reproduce**
1. Join JLL League
2. Click on 'https://impactapp.page.link/createTeam'
3. Teams Page should open

**Expected behavior**
Clicking on the Deeplink should show the error message of not able to access teams

**Screenshots**
NA

**Version [Check app's setting screen]:**
2.14.6

**Additional context**
NA

**Comment by parthanjaria** [comment]
deeplink opening teams page when in non-impact league issue resolved.

When we detect a deep link, there are many places it can be sent, so we have blocked entry into teams feature from any sort of deep link. 

Test:
- Click on this link : https://impactapp.page.link/createTeam
If you are not part of JLL/nonimpact league, then it should open the teams tab, else will show you a popup that this feature is blocked.
