### ISSUE TITLE
[BUG] buttons on end without pop up are not right for JLL and outdoor workout

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#41]
**Describe the bug**
The buttons say Yes No while the content doesn't ask any question.

**To Reproduce**
1. Go to JLL league and start workout.
2. Press finish and read the pop up content
3. Start an outdoor Workout and finish without covering 100 m
4. Read the pop up content

**Expected behavior**
Buttons should be Continue and End like in indoor workout popup.

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0.0
![Screenshot_20200513-141318](https://user-images.githubusercontent.com/64794999/81795477-ca647380-9529-11ea-8ade-f5f5e390395d.png)
![Screenshot_20200513-141422](https://user-images.githubusercontent.com/64794999/81795510-d3eddb80-9529-11ea-91c3-977c15b60e21.png)
![Screenshot_20200513-141938](https://user-images.githubusercontent.com/64794999/81795535-d8b28f80-9529-11ea-90b4-05d9575d4a9a.png)

**Additional context**

**Comment by sagrgpt** [comment]
@kanakagr We have identified the issue and resolved it for ver **2.15.0.1**
Closing this issue now. Please re-open if you face the same issue for the above-mentioned versions.
