### ISSUE TITLE
[BUG] Home screen stats incorrect 

### ISSUE THREAD

**Issue by sagrgpt** [Share-Impact/Android-Impact-Issues#43]
**Describe the bug**
Homescreen always shows 0.00 KM distance and 0 steps when in JLL league

**To Reproduce**
1. Join JLL league
2. Start a non impact workout
3. End a workout after completing min num of steps
4. Homescreen still shows 0.00 and 0

**Expected behavior**
My total distance and steps for the day should be reflected on the home screen

**Screenshots**
![Screenshot_2020-05-13-14-54-40-536_com sharesmile share](https://user-images.githubusercontent.com/11998999/81797547-92126480-952c-11ea-8477-bfbc016ac005.jpg)
![Screenshot_2020-05-13-14-54-33-810_com sharesmile share](https://user-images.githubusercontent.com/11998999/81797521-89219300-952c-11ea-91bd-66645aa3bb98.jpg)

**Version [Check app's setting screen]:** 2.15.0.0

**Additional context**
NA

**Comment by sagrgpt** [comment]
I just logged out and logged in.
The home screen stats now got updated but the distance value does not add up on the workout history screen. 
Also, the streak progress ring remains at zero. 

![InkedScreenshot_2020-05-13-15-50-32-866_com sharesmile share_LI](https://user-images.githubusercontent.com/11998999/81801442-11566700-9532-11ea-88b4-82d058bf661d.jpg)

**Comment by parthanjaria** [comment]
Issue is now resolved. The workout type was not set to non_impact_workout when the code was merged to develop. Due to which when stats data for non_impact_workouts were asked were set to 0. 

Test : 

Start a JLL workout. Do 0.1 km. then check for change in the home page stats
