### ISSUE TITLE
Clap count on Clap detail page not increasing when clapped from Post detail page

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#44]
**Describe the bug**
Clap count on Clap detail page not increasing when clapped from Post detail page

**To Reproduce**
1. clap from detail page 
2. click on claps to go clap detail page 
3. clap count is not updated even after refresh

**Expected behavior**
It should updated

**Screenshots**
shared video with anuja

**Version [Check app's setting screen]:**
2.14.6

**Additional context**

**Comment by parthanjaria** [comment]
Can you test this on v2.15.0.0? @NishantKhandelwal1

**Comment by sagrgpt** [comment]
Issue fixed for v 2.15.0.0
