### ISSUE TITLE
Clicking Clap notification doesn't show correct clap count

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#45]
**Describe the bug**
Clicking Clap notification doesn't show correct clap count

**To Reproduce**
1. check claps on the post and clap on it
2. ask someone to clap on the same post and click the notification
3. check clap count

**Expected behavior**
It should be correct

**Screenshots**

**Version [Check app's setting screen]:**
2.14.6

**Additional context**

**Comment by parthanjaria** [comment]
Can you test this on v2.15.0.0? @NishantKhandelwal1

**Comment by sagrgpt** [comment]
Issue fixed for v 2.15.0.0
