### ISSUE TITLE
Scroll and highlight comment

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#46]
**Describe the bug**
Scroll and highlight comment-> it takes me directly to the end of the page

**To Reproduce**
1. comment on the post which has 8+ comment
2. click on comment from post list page
3. it takes you to the detail page but animation is not happening

**Expected behavior**
Scroll and highlight comment

**Screenshots**
Video sent to anuja

**Version [Check app's setting screen]:**
2.14.6

**Additional context**

**Comment by Pawanm1990** [comment]
Unable to see highlight if comment less than 3

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 @Pawanm1990 We have found and resolved this issue for version **2.15.0.1**. Closing this issue now. Please reopen the issue if the mentioned version fails your tests.

**Comment by Pawanm1990** [comment]
Ok
