### ISSUE TITLE
[BUG] Donation popup visibile in Non-Impact League

### ISSUE THREAD

**Issue by sagrgpt** [Share-Impact/Android-Impact-Issues#48]
**Describe the bug**
I'm still able to see and click on the donation popup even though I'm in JLL league

**To Reproduce**
1. Go to Google settings and revoke Gfit permissions
2. Open the app
3. Join JLL league
4. Click on home screen
5. Donation popup is visible

or

1. Make sure donation popup is visible before joining the JLL league.
2. Join JLL league.
3. Complete a workout
4. Donation popup is visible

**Expected behavior**
Donation popup should never be visible if you are in a non-impact league

**Screenshots**
![Screenshot_2020-05-13-14-42-29-799_com sharesmile share](https://user-images.githubusercontent.com/11998999/81802504-d6553300-9533-11ea-96b4-155988185c1f.jpg)

**Version [Check app's setting screen]:** 2.15.0.0

**Additional context**

**Comment by parthanjaria** [comment]
I have resolved the issue. @sagrgpt I would like you to review this commit once before closing the issue. [https://github.com/Share-Impact/Impact_Android/commit/a3093ccedb69de06766885eadcf1279784fe7983](url)
