### ISSUE TITLE
[BUG] Not getting notification alert Team Request to Accept/Reject

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#49]
**Describe the bug**
Gaurav sent me a request to join the team, but not received notification alert.

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'Bell Icon'
3. Scroll down to 'Notification Center'
4. Received the notification alert but on when mobile locked not alert ring or vibrate.

**Expected behavior**
It should be ring/vibrate when mobile locked or open on notification center.

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**
NA

**Comment by AnujaPednekar** [comment]
The users who have exited JLL league are not getting push notifications. It will be taken care by backend later on.
