### ISSUE TITLE
[BUG] Team Page Scrolling working very slow

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#51]
**Describe the bug**
Team Page Scrolling working very slow.

**To Reproduce**
1. Go to 'Teams'
2. Click on 'Best Teams Group'
3. Scroll down to 'top to bottom'
4. See error- working very slow

**Expected behavior**
It should be smooth.

**Screenshots**
![WhatsApp Image 2020-05-13 at 6 25 06 PM](https://user-images.githubusercontent.com/64827333/81815650-dceda580-9547-11ea-909d-7ea9293361e1.jpeg)

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**
NA

**Comment by AnujaPednekar** [comment]
I checked the video sent by Pawan for this issue, scroll seemed smooth to me. 
As well as I asked other members to check this issue, they had no problem with it. Hence closing it.

Please reclose the issue if you face it again and send the video to me as well.
