### ISSUE TITLE
[BUG] App Crashed

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#52]
**Describe the bug**
App Crashed when I was in the Notification Center and Teams Page.

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'Notification Center and Teams Page'
3. Scroll down to 'Notification and Teams Page'
4. See error - App Crashed

**Expected behavior**
It should be not crashed.

**Screenshots**
![WhatsApp Image 2020-05-13 at 7 23 03 PM](https://user-images.githubusercontent.com/64827333/81821630-b0d62280-954f-11ea-8d32-24cc83a77d87.jpeg)

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**

**Comment by AnujaPednekar** [comment]
which notification did you check?

**Comment by Pawanm1990** [comment]
I don't remember. clicked on the notification center read messages scrolling towards up and down suddenly app crashed. and for Team went on "Best Freind&"

**Comment by sagrgpt** [comment]
We have found and resolved this issue for version **2.15.0.1**. Closing this issue now. Please reopen the issue if the mentioned version fails your tests.
