### ISSUE TITLE
[BUG]team accept notification issue

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#56]
**Describe the bug**
Click on team accept notification.... Doesn't show request in manage team. 
**To Reproduce**
1. Click on team accept notification. 

**Expected behavior**
Should show request in manage team. 

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**

**Comment by AnujaPednekar** [comment]
The user who exited JLL were not receiving push notification.
