### ISSUE TITLE
[BUG]LESS DISTANCE

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#60]
[User Id - 586826](https://ced.impactrun.com/userdetail/586826)
Run id - 28677942, 28352910
Device- Xiaomi

[User id- 581091](https://ced.impactrun.com/userdetail/581091)
Run id - 28354187
Device- Samsung

[User id - 156657](https://ced.impactrun.com/userdetail/156657)
Run id - 28529090
Device -Samsung

[User Id- 588012](https://ced.impactrun.com/userdetail/588012)
Run id - 28376474
Device- Lenovo

[User id- 586250](https://ced.impactrun.com/userdetail/586250)
Run id - 28580107
Device -One plus

[User id -584269](https://ced.impactrun.com/userdetail/584269)
Run id- 28534292
Device- Vivo

**Comment by sagrgpt** [comment]
[User id -590839](https://ced.impactrun.com/userdetail/590839)
Run id: Unknown
Device: Samsung SM-G930F

[User id- 588336](https://ced.impactrun.com/userdetail/588336)
Run id: 28580891
Device: Google Pixel 3 XL

**Comment by 24Kavisha** [comment]
User Id - 583102
Run ID - 29840270
Device - Google Pixel 3XL
--
