### ISSUE TITLE
[BUG] App crashed after clapping inside post

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#61]
**Describe the bug**
When I clapped on the post from inside the detail page and I clicked on the number of claps, the app crashed. (This happened twice with me)

**To Reproduce**
1. Tap on the post to open the detail page
2. Clap on the post multiple times
3. Click on the 'x claps' area
**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**

**Comment by sagrgpt** [comment]
@kaziamina We noted that a similar issue has been already created. Hence we will be closing this issue. All further communication will continue on issue #58
