### ISSUE TITLE
[BUG] Different amount raised on workout screen and notification drawer

### ISSUE THREAD

**Issue by kaziamina** [Share-Impact/Android-Impact-Issues#62]
**Describe the bug**
While doing outdoor workout, the time amount raised on workout screen showed 0rs but the one in the notification drawer should 1rs. Attaching screenshots

**To Reproduce**
1. Start workout
2. Complete atleast 0.05km distance
3. See amount in workout screen and notification bar

**Expected behavior**
Both the amounts should match.

**Screenshots**
![Screenshot_20200513-143726](https://user-images.githubusercontent.com/64898571/81908068-5f2ca700-95e6-11ea-9ed5-d210dd5177fa.jpg)
![Screenshot_20200513-143729](https://user-images.githubusercontent.com/64898571/81908077-60f66a80-95e6-11ea-82b6-13a6616c3067.jpg)

**Version [Check app's setting screen]:**
2.15.0.0.

**Additional context**

**Comment by sagrgpt** [comment]
@kaziamina Are you facing this issue only for outdoor workouts or for other workouts types as well?

**Comment by parthanjaria** [comment]
Shared the build with @kaziamina to test this. Change resolved in https://github.com/Share-Impact/Impact_Android/commit/3618d80d47379c55774b6ae5c395e09de444ab66
