### ISSUE TITLE
While steps donation I can only donate steps of yesterday at one time

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#63]
**Describe the bug**
I can only donate steps of yesterday at one time. Also when I return to the home screen then it showed me the total steps(around 5600) again  which I just donated. When I clicked on it It takes me a donation screen. On the donation screen, It was showing only today's steps.

**To Reproduce**
You should have yesterday and today's steps.
1. Donate steps
2. You still can see some steps in the daily activity screen

**Expected behavior**
All steps(Yesterday and today) should be donated at one time only

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 Can you attach the screenshots of the same so that we can understand the problem better?

**Comment by parthanjaria** [comment]
Given build to @NishantKhandelwal1 for testing the issue.
