### ISSUE TITLE
[BUG]app crashes when click on send button in post detail page. 

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#64]
**Describe the bug**
App get crashes when clicking on send button in post detail page..... While commenting. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version [Check app's setting screen]:**
Ver. 2.15.0.0

**Additional context**

**Comment by parthanjaria** [comment]
Can you share which post you tried to comment on?

**Comment by AnujaPednekar** [comment]
Duplicate of Issue #52
