### ISSUE TITLE
[BUG] Unable to connect to Gfit

### ISSUE THREAD

**Issue by 24Kavisha** [Share-Impact/Android-Impact-Issues#68]
**Describe the bug**
A text showing connecting to Gfit ...
But the user is able to track passive steps

**To Reproduce**
1. Go to 'Current streak'
2. It should show the passive steps

**Expected behavior**
Text displaying connecting to Gfit should be removed.

**Screenshots**
![img_1589380077009](https://user-images.githubusercontent.com/64829704/82023663-3cfd5c80-96ac-11ea-9c78-3348bcd565ef.jpeg)

**Version [Check app's setting screen]:**

**Additional context**

**Comment by AnujaPednekar** [comment]
Please mention user id

**Comment by 24Kavisha** [comment]
User ID - 573142
Ver- 2.14.6

**Comment by parthanjaria** [comment]
Logs seen : ApiException: 10: SecurityException: com.google.step_count.delta requires android.permission.ACTIVITY_RECOGNITION

Need to explicitly ask Activity_Recognition permission to the user.

**Comment by parthanjaria** [comment]
@24Kavisha @adrija25 until we solve this bug, you can ask the user to grand the "Physical Activity" permission from app settings page.

Please check these screens :

![Screenshot_20200522-114133](https://user-images.githubusercontent.com/14540386/82636969-6de80f00-9c21-11ea-9116-51fce89ce930.png)
![Screenshot_20200522-114142](https://user-images.githubusercontent.com/14540386/82636985-73ddf000-9c21-11ea-9ce3-5a2f3b8aeef4.png)
![Screenshot_20200522-114149](https://user-images.githubusercontent.com/14540386/82637327-28781180-9c22-11ea-94b1-deab2302856b.png)

**Comment by parthanjaria** [comment]
Have made the respective changes by upgrading the compileSDK to 29. The user will get the prompt to give permission for PhysicalActivity. Please let us know if the issue still persists.
