### ISSUE TITLE
Duplicate passive workouts

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#69]
CED : https://ced.impactrun.com/userdetail/561885
Screenshot attached.
Version no. 2.13.6
device : PANASONIC Eluga_Arc_2

![Screenshot_20200515-143145](https://user-images.githubusercontent.com/8169016/82035386-1398fc80-96bd-11ea-9cd2-b200e7f3b419.png)
![Screenshot_20200515-143134](https://user-images.githubusercontent.com/8169016/82035392-1562c000-96bd-11ea-8669-31aa0e70c6cf.png)
![Screenshot_20200515-143152](https://user-images.githubusercontent.com/8169016/82035394-15fb5680-96bd-11ea-8f24-e4854ae30a6c.png)

**Comment by sagrgpt** [comment]
Duplicate issue #24
