### ISSUE TITLE
[BUG] Streak ring shows Progress but Steps shows O

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#7]
**Describe the bug**
I opened the app to donate steps, but it showed 0 steps..the streak ring however showed progress.
So I clicked on the steps and in the activity screen it showed 400+steps.
After donating, it shows 75 steps available.

**To Reproduce**
1. Go to 'Home Screen'
2. Click on 'Steps'

**Expected behavior**
Can't say...explained as much as I could.

**Screenshots**
![Screenshot_2020-05-05-14-22-29-640_com sharesmile share](https://user-images.githubusercontent.com/64792558/81049856-a5924f80-8edc-11ea-9a01-a39d06e8342d.jpg)
![Screenshot_2020-05-05-14-23-25-131_com sharesmile share](https://user-images.githubusercontent.com/64792558/81049884-b4790200-8edc-11ea-9875-726117d810c2.jpg)

**Version [Check app's setting screen]:**2.14.0

**Additional context**

**Comment by adrija25** [comment]
![Screenshot_2020-05-05-14-22-21-554_com sharesmile share](https://user-images.githubusercontent.com/64792558/81049948-d4a8c100-8edc-11ea-81a9-e6ef6566be24.jpg)

**Comment by adrija25** [comment]
![Screenshot_2020-05-05-14-22-21-554_com sharesmile share](https://user-images.githubusercontent.com/64792558/81050066-015cd880-8edd-11ea-8233-cb3103143dbe.jpg)

**Comment by sagrgpt** [comment]
@adrija25 Did join/exit JLL league when this issue occurred?

**Comment by adrija25** [comment]
I don't remember 😅

**Comment by sagrgpt** [comment]
@adrija25 We have identified and fixed this issue. Please test **v2.15.0.0** to ensure the same.
Closing this issue now. You are welcome to re-open the issue if the above mentioned version fails your test.
