### ISSUE TITLE
[BUG] Not receiving passive notification 

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#73]
**Describe the bug**
I'm not getting passive notification even after completing my daily goal and covering more than 1000 steps daily

**To Reproduce**
NA

**Expected behavior**
Should get a notification to donate passive steps

**Screenshots**
NA

**Version [Check app's setting screen]:**
2.15.0.0

**Additional context**
I'm not a part of JLL league

**Comment by apunuj** [comment]
@aayush-khandelwal 
I have worked on this. Hope you are getting the notifications now?

**Comment by aayush-khandelwal** [comment]
Yes. I'm getting the notification

**Comment by apunuj** [comment]
Solved, hence closing.
