### ISSUE TITLE
[BUG] Same team visible twice on searching

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#74]
**Describe the bug**
I searched Impact name in the join team option and I noticed Impact Goa was visible twice.

**Screenshots**
![Screenshot_2020-05-18-17-39-08-246_com sharesmile share](https://user-images.githubusercontent.com/64792558/82211879-37637900-992f-11ea-837e-3a266feab234.jpg)

![Screenshot_2020-05-18-17-39-36-082_com sharesmile share](https://user-images.githubusercontent.com/64792558/82211870-30d50180-992f-11ea-876d-d6d885911e14.jpg)
![Screenshot_2020-05-18-17-39-40-084_com sharesmile share](https://user-images.githubusercontent.com/64792558/82211891-3c282d00-992f-11ea-8a7b-c6abac9fee99.jpg)

**Version [Check app's setting screen]:** 2.15.0

**Additional context**

**Comment by AnujaPednekar** [comment]
@NishantKhandelwal1 Please check this.

**Comment by AnujaPednekar** [comment]
Issue resolved by backend. @adrija25 Please check.
