### ISSUE TITLE
[BUG] In clap detail page, Public profile should be open while clicking whole cell.

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#75]
**Describe the bug**
 In clap detail page, Public profile should be open while clicking whole cell.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0

**Additional context**

**Comment by AnujaPednekar** [comment]
Made the whole cell clickable to open profile
