### ISSUE TITLE
[BUG]Not Counting Steps,Distance and Calories 

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#76]
**Describe the bug**
During workout app not counting steps, distance, and calories.

**To Reproduce**
1. Go to 'JLL League Home Page.'
2. Click on 'Workout Button'
3. Scroll down to 'Workout Page'
4. See error- Not counting

**Expected behavior**
It should be count steps, distance and calories.

**Screenshots**
![Screenshot_20200518-164000](https://user-images.githubusercontent.com/64827333/82225862-5b30ba00-9943-11ea-84bd-1aafed327bf7.png)

**Version [Check app's setting screen]:**
2.15.0 (JLL)

**Additional context**
NA

**Comment by sagrgpt** [comment]
Unable to reproduce this issue. Please reopen when you face this issue again.
