### ISSUE TITLE
[BUG] Clicking on clap notification doesn't show updated claps on post detail page

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#77]
**Describe the bug**
Clicking on push notification of claps or from notification center opens the post detail page. But clap count is not updated. Clicking on clap list shows the updated count 

**To Reproduce**
1. Click on clap notification either from notification center or push notification
2. See the clap count
3. Click to view the clap list
4. Match with the clap count

**Expected behavior**
Clap count should instantly update on post detail page. It's correctly visible on team page where all posts are shown.

**Screenshots**
![Screenshot_20200518-170601](https://user-images.githubusercontent.com/64794999/82237604-8d4a1800-9953-11ea-80e2-225f9ebc48b0.png)
![Screenshot_20200518-170606](https://user-images.githubusercontent.com/64794999/82237616-920ecc00-9953-11ea-93f1-85a5485a8e02.png)

**Version [Check app's setting screen]:**
2.15.0

**Additional context**

**Comment by parthanjaria** [comment]
Issue is solved in v2.15.1. Please feel free to re-open the bug if found again.
