### ISSUE TITLE
[BUG] Receiving passive donation notification even after being part of JLL league

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#8]
**Describe the bug**
Receiving passive donation notification even after being part of JLL league

**To Reproduce**
1. Go to notification drawer of your phone
2. Click on Passive notification from Impact App
3. Try donating the steps and see error of less than 250 steps
4. Check whether JLL cause is there

**Expected behavior**
Notification shouldn't come for JLL league users

**Screenshots**
Attached 

**Version [Check app's setting screen]:**
2.14.0

**Additional context**
NA

**Comment by parthanjaria** [comment]
@NishantKhandelwal1 Please look into this issue.

**Comment by apunuj** [comment]
@aayush-khandelwal can't see screenshots. Also can you share your user_id if you know it?

**Comment by aayush-khandelwal** [comment]
I am sending you a screen recording of the issue

**Comment by aayush-khandelwal** [comment]
User ID: 3124

**Comment by apunuj** [comment]
Closing, since it's resolved.
