### ISSUE TITLE
[BUG]Clicking on clap notification, showing 0 claps in Post.

### ISSUE THREAD

**Issue by gauravchauhan677** [Share-Impact/Android-Impact-Issues#82]
**Describe the bug**
Clicking on clap notification, showing 0 claps in Post Detail Page.
It also shows when 0 claps when Clicking on the notification in Notification Center.
After some time it shows correctly when Clicking clap notification in notification center.

**To Reproduce**

**Expected behavior**
should show clap in the Post detail page.

**Screenshots**

**Version [Check app's setting screen]:**
2.15.0

**Additional context**

**Comment by parthanjaria** [comment]
Duplicate to #77
