### ISSUE TITLE
Getting phone number in wrong format

### ISSUE THREAD

**Issue by NishantKhandelwal1** [Share-Impact/Android-Impact-Issues#86]
**Describe the bug**
Getting phone number in the wrong format for some users
"phone_number"='+965.9982.1908'
"user_id" = '548288'

**To Reproduce**

**Expected behavior**
it should come without special characters

**Screenshots**

**Version [Check app's setting screen]:**

**Additional context**
Source: logz.io

**Comment by parthanjaria** [comment]
The user will be able to only add these characters : (0123456789+)
