### ISSUE TITLE
[BUG] Getting notification (red mark/number) for old notifications

### ISSUE THREAD

**Issue by adrija25** [Share-Impact/Android-Impact-Issues#9]
**Describe the bug**
I had opened notification center yesterday.
However, when I opened the app I could see 5+ notification marked.
When I opened it, It had the old notifications from a team I had already Exited.

**To Reproduce**
1. Go to 'Homescreen'
2. Click on 'Notification icon'
3.Go to 'Team'
4.Click 'Exit team'
5.Open 'Homescreen' next day

**Expected behavior**

**Screenshots**
![Screenshot_2020-05-05-19-16-15-371_com sharesmile share](https://user-images.githubusercontent.com/64792558/81084139-1e140300-8f13-11ea-86b7-c7fb123f0e3d.jpg)

**Version [Check app's setting screen]:**2.14.0

**Additional context**

**Comment by parthanjaria** [comment]
@adrija25 can you share the video for the same.

**Comment by adrija25** [comment]
I will try to reproduce the issue and share the same.

**Comment by parthanjaria** [comment]
As per our conversation, this is the expected functionality. @nikhilk90 addy is suggesting on each login, we should not see +4 which we show currently if the user has shown that.

**Comment by adrija25** [comment]
Yes it kinda defies the purpose of new notification if I have to keep opening for old notifications too..makes it less interesting..

**Comment by parthanjaria** [comment]
@adrija25 are you still facing this issue? After our discussion have you teste this?

**Comment by adrija25** [comment]
Once...i forgot to record it or click screenshot.

**Comment by parthanjaria** [comment]
Ok, try again. and let me know.

**Comment by parthanjaria** [comment]
@adrija25 I am closing the issue now. If the issue still persists please feel free to reopen the issue.
