### ISSUE TITLE
[BUG] 15 days badge notification takes to 7 days streak post

### ISSUE THREAD

**Issue by AnujaPednekar** [Share-Impact/Android-Impact-Issues#91]
**Describe the bug**
Clicking 15 days or 30 days streak badge notification from notification centre takes to 7 days streak post. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the notification centre 
2. Click on notification of a friend completed 15 days or 30 days streak
3. Redirects me to 7 days streak completed post

**Reported by** - Kanak Agarwal

**Expected behaviour**
Should take me to 15 days post

**Comment by AnujaPednekar** [comment]
@NishantKhandelwal1 Please look into this

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 Any updates?

**Comment by NishantKhandelwal1** [comment]
@sagrgpt This issue is fixed. We can close it

**Comment by sagrgpt** [comment]
Kar de bhai close.

**Comment by NishantKhandelwal1** [comment]
@sagrgpt mujhe option ni dikh rha yr

**Comment by NishantKhandelwal1** [comment]
This issue is solved
