### ISSUE TITLE
[BUG]Thank you screen did not appear after JLL workout

### ISSUE THREAD

**Issue by AnujaPednekar** [Share-Impact/Android-Impact-Issues#92]
**Describe the bug**
Kanak did a workout and ended it, workout got created but TY screen didn't appear.

**Workout Details** - 18th May, 5:43PM

**Version [Check app's setting screen]:** 2.15.0.0

**Comment by apunuj** [comment]
My dad faced the 'Too Short' pop up variant of this bug. He finished 1.97km of indoor workout in 2.15.2. But when he clicked on finish workout, he got the too short popup. He had to kill the app from background and restart to use Impact again.

Later when I checked, I could see this workout created at the backend in CED.

**Comment by apunuj** [comment]
I recommend moving this bug to high priority/blocker because it is an experience killer.
@sagrgpt @AnujaPednekar @parthanjaria

**Comment by sagrgpt** [comment]
We have identified and fixed this issue on v2.16.7. 
Please reopen the issue of not fixed for v2.16.7+
