### ISSUE TITLE
Star ribbon on changemaker badge 

### ISSUE THREAD

**Issue by aayush-khandelwal** [Share-Impact/Android-Impact-Issues#93]
**Describe the bug**
Changemaker badge in team post shows star ribbon

**To Reproduce**
Na

**Expected behavior**
Ribbon should not come for changemaker badge

**Screenshots**
![Screenshot_20200522-200949](https://user-images.githubusercontent.com/64794993/82679420-92b3a500-9c68-11ea-8f59-986191e46b76.jpg)

**Version [Check app's setting screen]:**
2.15.0

**Additional context**
No

**Comment by parthanjaria** [comment]
@aayush-khandelwal can you let me know which team is this showing?

**Comment by aayush-khandelwal** [comment]
Impact Goa

**Comment by parthanjaria** [comment]
Issue is resolved after 2.16.19
