### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 24Kavisha** [Share-Impact/Android-Impact-Issues#94]
**Describe the bug**
Unable to track steps/ 0 steps counted

**To Reproduce**
1. Go to start workout
No steps are tracked

**Expected behavior**
3km workout should be tracked

**Screenshots**

**Version [Check app's setting screen]:**
2.14.7

**Additional context**
User ID - 588012
Device name - Lenovo

**Comment by sagrgpt** [comment]
Duplicate Issue #60 
We noticed that this an already closed issue. The details on this have been provided on the slack changemake_happens channel. Please refer to them.
