### ISSUE TITLE
Supercard is thinner and smaller than cause card

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#95]
**Describe the bug**
Supercard should be of same size as cause card imo but it's smaller

**To Reproduce**
1. Update to 2.16.0.1
2. Open the app
3. Swipe to see supercard
4. Compare the size with cause card

**Expected behavior**

**Screenshots**
![Screenshot_20200603-122439](https://user-images.githubusercontent.com/64794999/83606097-a8916600-a596-11ea-9588-d1b6eb360283.png)

**Version [Check app's setting screen]:**
2.16.0.1

**Additional context**

**Comment by sagrgpt** [comment]
All issue with respect to supercard UI has been resolved in the v 2.16.0 and above. 
Closing this issue now. Please reopen the issue if the problem still exists.
