### ISSUE TITLE
Feed Link not attached on social media

### ISSUE THREAD

**Issue by Pawanm1990** [Share-Impact/Android-Impact-Issues#96]
When sharing feed blog on social media only picture deliver not able to find links of page
![Screenshot_20200603-160407](https://user-images.githubusercontent.com/64827333/83627776-19477b00-a5b5-11ea-963b-dca2a30d97d3.png)

**Comment by sagrgpt** [comment]
Please create an issue using the already existing templates.

**Comment by parthanjaria** [comment]
@Pawanm1990 as discussed on call, Facebook, instagram and linkedIn only allow one media to be shared(either image or text)
