### ISSUE TITLE
Incorrect toast of post not loading

### ISSUE THREAD

**Issue by nikhilk90** [Share-Impact/Android-Impact-Issues#97]
Whenever I visit a teams post from notification center it shows me a toast that unable to load post while I can see the post. 
![Screenshot_20200603-164803](https://user-images.githubusercontent.com/8169016/83630802-0b482900-a5ba-11ea-833b-ef11029f7241.jpg)

Version 2.16.0.1

**Comment by sagrgpt** [comment]
Please follow the template while reporting an issue.

**Comment by parthanjaria** [comment]
It was showing the toast when getting a null value from db.

**Comment by sagrgpt** [comment]
@parthanjaria can you update the version number before closing the issue so that the author knows which version to update to so that they can check this issue is resolved.
