### ISSUE TITLE
[BUG] Feed not loading on top

### ISSUE THREAD

**Issue by kanakagr** [Share-Impact/Android-Impact-Issues#98]
**Describe the bug**
I clicked on the new feed notification on feed icon and it opened on an old feed post. Had to scroll down to see the latest post.

**To Reproduce**
1. Open app
2. Click on new feed red notification
3. See if you see the latest feed

**Expected behavior**
It should always open on top

**Screenshots**

**Version [Check app's setting screen]:**
2.16.0.1

**Additional context**

**Comment by sagrgpt** [comment]
@Share-Impact/backend-developers Can you please take a look at this?

**Comment by NishantKhandelwal1** [comment]
@sagrgpt I'll check this issue

**Comment by sagrgpt** [comment]
@NishantKhandelwal1 Any update?

**Comment by NishantKhandelwal1** [comment]
@kanakagr Fixed this issue
